# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FontOutline
                                 A QGIS plugin
 this plugin make font outline
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-29
        copyright            : (C) 2024 by raino
        email                : zraino@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
 d;stlyelgki nqkwierytpf;fr4367dhrcfnguwy
"""

try:
    import fontTools
except ImportError:
    print("no fonttool.....")
    import sys
    import os
    sys.path.append(os.path.dirname(__file__))

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FontOutline class from file FontOutline.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .font_outline import FontOutline
    return FontOutline(iface)
