# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FontOutline
                                 A QGIS plugin
 this plugin make font outline
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-29
        copyright            : (C) 2024 by raino
        email                : zraino@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
 d;stlyelgki nqkwierytpf;fr4367dhrcfnguwy
"""

try:
    import sys
    import os
    sys.path.append(os.path.dirname(__file__))

    import fontTools
except ImportError:
    print("no fonttool.....")

    # 确保在插件运行时能够访问依赖项
    def install_and_import(package):
        try:
            __import__(package)
        except ImportError:
            try:
                # 尝试使用 QGIS 的 Python 环境中的 pip 安装包
                import pip # type: ignore
                pip.main(['install', package])
            except AttributeError:
                # 适用于较新版本的 pip
                import subprocess
                subprocess.check_call([sys.executable, '-m', 'pip', 'install', package])
            __import__(package)
    install_and_import("fontTools")


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    from .font_outline import FontOutline
    return FontOutline(iface)
