# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FontOutlineDialog
                                 A QGIS plugin
 this plugin make font outline
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-29
        git sha              : $Format:%H$
        copyright            : (C) 2024 by raino
        email                : zraino@qq.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
# debug conveniently
Ui_FontOutlineDialogBase, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), "ui", 'main_ui.ui'))

# run in production
# from .ui.main_ui import Ui_FontOutlineDialogBase

class FontOutlineDialog(QtWidgets.QDialog, Ui_FontOutlineDialogBase):
    def __init__(self, parent=None):
        """Constructor."""
        super(FontOutlineDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.dlg.lineEdit.textChanged.connect(self.on_input_changed)

    def on_input_changed(self, text):
        if text is "" or text is None:
            # TODO: 输入字符空值判断
            print("输入字符串不能为空。")
