# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'font_outline_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FontOutlineDialogBase(object):
    def setupUi(self, FontOutlineDialogBase):
        FontOutlineDialogBase.setObjectName("FontOutlineDialogBase")
        FontOutlineDialogBase.resize(647, 495)
        self.button_box = QtWidgets.QDialogButtonBox(FontOutlineDialogBase)
        self.button_box.setGeometry(QtCore.QRect(60, 410, 521, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.lineEdit = QtWidgets.QLineEdit(FontOutlineDialogBase)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 201, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(FontOutlineDialogBase)
        self.label.setGeometry(QtCore.QRect(50, 20, 71, 21))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(FontOutlineDialogBase)
        self.label_3.setGeometry(QtCore.QRect(80, 80, 51, 21))
        self.label_3.setObjectName("label_3")
        self.mFontButton = QgsFontButton(FontOutlineDialogBase)
        self.mFontButton.setGeometry(QtCore.QRect(160, 80, 191, 31))
        self.mFontButton.setObjectName("mFontButton")
        self.label_4 = QtWidgets.QLabel(FontOutlineDialogBase)
        self.label_4.setGeometry(QtCore.QRect(70, 140, 61, 21))
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(FontOutlineDialogBase)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 200, 541, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mExtentGroupBox = QgsExtentGroupBox(self.verticalLayoutWidget)
        self.mExtentGroupBox.setObjectName("mExtentGroupBox")
        self.verticalLayout.addWidget(self.mExtentGroupBox)
        self.mQgsExternalResourceWidget = QgsExternalResourceWidget(FontOutlineDialogBase)
        self.mQgsExternalResourceWidget.setGeometry(QtCore.QRect(160, 140, 201, 31))
        self.mQgsExternalResourceWidget.setObjectName("mQgsExternalResourceWidget")

        self.retranslateUi(FontOutlineDialogBase)
        self.button_box.accepted.connect(FontOutlineDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(FontOutlineDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FontOutlineDialogBase)

    def retranslateUi(self, FontOutlineDialogBase):
        _translate = QtCore.QCoreApplication.translate
        FontOutlineDialogBase.setWindowTitle(_translate("FontOutlineDialogBase", "Font Outline"))
        self.label.setText(_translate("FontOutlineDialogBase", "base_str:"))
        self.label_3.setText(_translate("FontOutlineDialogBase", "font:"))
        self.label_4.setText(_translate("FontOutlineDialogBase", "export:"))
from qgsextentgroupbox import QgsExtentGroupBox
from qgsexternalresourcewidget import QgsExternalResourceWidget
from qgsfontbutton import QgsFontButton
