# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'font_outline_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FontOutlineDialogBase(object):
    def setupUi(self, FontOutlineDialogBase):
        FontOutlineDialogBase.setObjectName("FontOutlineDialogBase")
        FontOutlineDialogBase.resize(596, 342)
        self.button_box = QtWidgets.QDialogButtonBox(FontOutlineDialogBase)
        self.button_box.setGeometry(QtCore.QRect(50, 220, 521, 41))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.lineEdit = QtWidgets.QLineEdit(FontOutlineDialogBase)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 201, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.input_label = QtWidgets.QLabel(FontOutlineDialogBase)
        self.input_label.setGeometry(QtCore.QRect(50, 20, 91, 21))
        self.input_label.setObjectName("input_label")
        self.save_label = QtWidgets.QLabel(FontOutlineDialogBase)
        self.save_label.setGeometry(QtCore.QRect(70, 130, 61, 21))
        self.save_label.setObjectName("save_label")
        self.input_label_2 = QtWidgets.QLabel(FontOutlineDialogBase)
        self.input_label_2.setGeometry(QtCore.QRect(60, 80, 91, 21))
        self.input_label_2.setObjectName("input_label_2")
        self.location_text = QtWidgets.QLineEdit(FontOutlineDialogBase)
        self.location_text.setGeometry(QtCore.QRect(160, 70, 201, 31))
        self.location_text.setInputMask("")
        self.location_text.setText("40.3504,116.2148")
        self.location_text.setReadOnly(False)
        self.location_text.setClearButtonEnabled(True)
        self.location_text.setObjectName("location_text")
        self.saveFileWidget = QgsFileWidget(FontOutlineDialogBase)
        self.saveFileWidget.setGeometry(QtCore.QRect(160, 130, 251, 27))
        self.saveFileWidget.setObjectName("saveFileWidget")

        self.retranslateUi(FontOutlineDialogBase)
        self.button_box.accepted.connect(FontOutlineDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(FontOutlineDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FontOutlineDialogBase)

    def retranslateUi(self, FontOutlineDialogBase):
        _translate = QtCore.QCoreApplication.translate
        FontOutlineDialogBase.setWindowTitle(_translate("FontOutlineDialogBase", "Font Outline"))
        self.lineEdit.setPlaceholderText(_translate("FontOutlineDialogBase", "any text..."))
        self.input_label.setText(_translate("FontOutlineDialogBase", "input_str :"))
        self.save_label.setText(_translate("FontOutlineDialogBase", "save:"))
        self.input_label_2.setText(_translate("FontOutlineDialogBase", "location:"))
        self.location_text.setPlaceholderText(_translate("FontOutlineDialogBase", "40.3504,116.2148"))
from qgsfilewidget import QgsFileWidget
